/*
 * softTim_definitions.h
 *
 *  Created on: Apr 17, 2023
 *      Author: NilRi
 */

#ifndef INC_SOFTTIM_DEFINITIONS_H_
#define INC_SOFTTIM_DEFINITIONS_H_


/***TASK ACTIVE PERIODS IN MS***/
#define OBC_ACTIVE_PERIOD 			1000
#define COMMS_ACTIVE_PERIOD 		1000
#define ADCS_ACTIVE_PERIOD 			1000
#define PAYLOAD_ACTIVE_PERIOD 		1000
#define EPS_ACTIVE_PERIOD 			1000

/***TASK SUSPENDED PERIODS IN MS***/
#define OBC_SUSPENDED_PERIOD 		1000
#define COMMS_SUSPENDED_PERIOD 		1000
#define ADCS_SUSPENDED_PERIOD 		1000
#define PAYLOAD_SUSPENDED_PERIOD 	1000
#define EPS_SUSPENDED_PERIOD 		1000

#endif /* INC_SOFTTIM_DEFINITIONS_H_ */
